version: '3'

services:
  blog:
    container_name: blog-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/
    working_dir: /var/www/      
    networks:
      - laravel

  nginx:
    container_name: nginx-app
    image: nginx
    restart: unless-stopped    
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    working_dir: /var/www/
    networks:
      - laravel

  db:
    image: mysql
    container_name: mysql-app
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel

networks:
  laravel:
    driver: bridge